In [1]:
import sys
print(sys.executable)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import warnings
warnings.filterwarnings("ignore")

# ── 0. DATEI LADEN ───────────────────────────────────────────
# Pfad anpassen!
CSV_PATH = "../en.openfoodfacts.org.products 2.csv"

cols = ["additives_n", "additives_tags", "additives_en", "additives"]
df = pd.read_csv(CSV_PATH, sep="	", usecols=cols, low_memory=False)

# Füllrate aller Spalten
print(df[cols].notna().mean().round(2) * 100)

# Alle Paare auf Überlappung prüfen
import itertools

for col1, col2 in itertools.combinations(cols, 2):
    beide = df[[col1, col2]].notna().all(axis=1).sum()
    print(f"{col1} + {col2}: beide befüllt in {beide} Zeilen")

# Zeilen wo mehrere Spalten gleichzeitig befüllt sind
mask = df[cols].notna().sum(axis=1) >= 2
df[cols][mask].head(50)

import pandas as pd
# Paarweise Überlappung aller 4 Spalten (wie oft sind je 2 gleichzeitig befüllt?)
overlap = pd.DataFrame(index=cols, columns=cols, dtype=float)
for c1 in cols:
    for c2 in cols:
        overlap.loc[c1, c2] = df[[c1, c2]].notna().all(axis=1).sum()
overlap.astype(int)

/opt/homebrew/opt/python@3.11/bin/python3.11
additives_n       28.0
additives_tags    15.0
additives_en      15.0
additives          0.0
dtype: float64
additives_n + additives_tags: beide befüllt in 697089 Zeilen
additives_n + additives_en: beide befüllt in 697089 Zeilen
additives_n + additives: beide befüllt in 33 Zeilen
additives_tags + additives_en: beide befüllt in 697089 Zeilen
additives_tags + additives: beide befüllt in 29 Zeilen
additives_en + additives: beide befüllt in 29 Zeilen

                additives_n  additives_tags  additives_en  additives
additives_n         1280985          697089        697089         33
additives_tags       697089          697089        697089         29
additives_en         697089          697089        697089         29
additives                33              29            29         33

In [2]:
# Zeilen wo mehrere Spalten gleichzeitig befüllt sind
mask = df[cols].notna().sum(axis=1) >= 2
df[cols][mask].head(20)

,additives_n,additives_tags,additives_en,additives
4,2,"en:e330,en:e955","E330 - Citric acid,E955 - Sucralose",NaN
13,1,en:e955,E955 - Sucralose,NaN
15,3,"en:e331,en:e422,en:e503","E331 - Sodium citrates,E422 - Glycerol,E503 - ...",NaN
19,6,"en:e322,en:e322i,en:e331,en:e422,en:e500,en:e503","E322 - Lecithins,E322i - Lecithin,E331 - Sodiu...",NaN
21,2,"en:e415,en:e955","E415 - Xanthan gum,E955 - Sucralose",NaN
26,6,"en:e322,en:e322i,en:e331,en:e422,en:e500,en:e503","E322 - Lecithins,E322i - Lecithin,E331 - Sodiu...",NaN
29,4,"en:e140,en:e140i,en:e330,en:e331,en:e331iii,en...","E140 - Chlorophylls and Chlorophyllins,E140i -...",NaN
30,1,en:e250,E250 - Sodium nitrite,NaN
38,5,"en:e296,en:e297,en:e334,en:e412,en:e960","E296 - Malic acid,E297 - Fumaric acid,E334 - L...",NaN
40,4,"en:e330,en:e331,en:e440,en:e903","E330 - Citric acid,E331 - Sodium citrates,E440...",NaN
45,4,"en:e1201,en:e304,en:e304i,en:e460,en:e460i,en:...","E1201 - Polyvinylpyrrolidone,E304 - Fatty acid...",NaN
52,4,"en:e340,en:e466,en:e950,en:e955","E340 - Potassium phosphates,E466 - Sodium carb...",NaN
53,4,"en:e1400,en:e466,en:e551,en:e570","E1400 - Dextrin,E466 - Sodium carboxy methyl c...",NaN
54,1,en:e440,E440 - Pectins,NaN
55,1,en:e968,E968 - Erythritol,NaN
57,3,"en:e322,en:e322i,en:e422","E322 - Lecithins,E322i - Lecithin,E422 - Glycerol",NaN
74,5,"en:e330,en:e415,en:e422,en:e502,en:e621","E330 - Citric acid,E415 - Xanthan gum,E422 - G...",NaN
77,1,en:e330,E330 - Citric acid,NaN
85,1,en:e415,E415 - Xanthan gum,NaN
87,7,"en:e129,en:e133,en:e296,en:e297,en:e331,en:e95...","E129 - Allura red,E133 - Brilliant blue FCF,E2...",NaN

In [ ]:
# Nimm packaging_en, falls leer dann packaging als Fallback
# Reihenfolge = Priorität (erste Spalte hat Vorrang)
df['additives_combined'] = (
    df['additives_tags']
    .fillna(df['additives_en'])
)